### ISSUE TITLE
mvn spring-boot:run fails 

### ISSUE THREAD

**Issue by paskos** [spring-cloud-samples/eureka#14]
when I try mvn sprting-boot:run I get
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]
> [ERROR]   The project org.demo:eureka:0.0.1-SNAPSHOT (/Users/pgehl/Documents/github/spring/cloud/eureka/pom.xml) has 1 error
> [ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-netflix:pom:1.0.2.BUILD-SNAPSHOT @ org.springframework.cloud:spring-cloud-starter-parent:[unknown-version], /Users/pgehl/.m2/repository/org/springframework/cloud/spring-cloud-starter-parent/1.0.2.BUILD-SNAPSHOT/spring-cloud-starter-parent-1.0.2.BUILD-SNAPSHOT.pom, line 31, column 16 -> [Help 2]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by spencergibb** [comment]
@paskos the snapshots were missing from our snapshot maven repo yesterday, but I fixed that.  Can you try `mvn --update-snapshots spring-boot:run`.

**Comment by paskos** [comment]
I still have the problem.

**Comment by spencergibb** [comment]
maybe `rm -rf ~/.m2/repository/org/springframework/cloud`?

**Comment by paskos** [comment]
nope :)

ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.demo:eureka:0.0.1-SNAPSHOT (/Users/pgehl/Documents/github/spring/cloud/eureka/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.cloud:spring-cloud-netflix:pom:1.0.2.BUILD-SNAPSHOT @ org.springframework.cloud:spring-cloud-starter-parent:[unknown-version], /Users/pgehl/.m2/repository/org/springframework/cloud/spring-cloud-starter-parent/1.0.2.BUILD-SNAPSHOT/spring-cloud-starter-parent-1.0.2.BUILD-SNAPSHOT.pom, line 31, column 16 -> [Help 2]

**Comment by spencergibb** [comment]
Do you have a `~/.m2/settings.xml`?  I have verified the poms and jars are in the snapshot repo.  There must be some other issue on your end that I can't see.  Can you build the project? `mvn package`?  Maybe try with the `--debug` flag.
