### ISSUE TITLE
Eureka server start failed

### ISSUE THREAD

**Issue by liangwn** [spring-cloud-samples/eureka#28]
java.lang.NoSuchMethodError:org.spring.framework.boot.SpringApplicationBuilder.showBanner(Z)Lorg/springframework/boot/builder/SpringApplicationBuilder;

**Comment by spencergibb** [comment]
I'm unable to recreate this problem. Can you provide more details about how you get that error?

**Comment by liangwn** [comment]
maybe that's library compatibility issue, but I get new issue, when I start eureka server, it just shows with xml not html, do you know the reason?

**Comment by spencergibb** [comment]
No, can you share a project that recreates the problem?

**Comment by liangwn** [comment]
I recreate one new project， this issue is gone， but I get xml not html when I start eureka server.

**Comment by liangwn** [comment]
start eureka server and get xml not html, with localhost:port
<com.netflix.eureka.util.StatusInfo>
<generalStats>
<environment>test</environment>

**Comment by spencergibb** [comment]
I repeat:
>  can you share a project that recreates the problem?

**Comment by liangwn** [comment]
sorry，I only get this issue in company desktop, so I could not share the project. In my labtop it works well.

Thanks again! I think we could close this issue.
