### ISSUE TITLE
Eureka Server Start Up Error

### ISSUE THREAD

**Issue by rahulgopu** [spring-cloud-samples/eureka#49]
Information:java: Errors occurred while compiling module 'discovery-server'
Information: javac 11.0.4 was used to compile java sources
Information: Module "discovery-server" was fully rebuilt due to project configuration/dependencies changes
Information:2/4/20, 2:09 PM - Build completed with 2 errors and 0 warnings in 2 s 809 ms
Error:java: error reading /Users/user/.m2/repository/com/sun/jersey/jersey-server/1.19.1/jersey-server-1.19.1.jar; zip file is empty
/Users/user/Desktop/discovery-server/src/main/java/com/miracle/discoveryserver/DiscoveryServerApplication.java
Error:(1, 1) java: cannot access com.miracle.discoveryserver
  Error reading file /Users/user/.m2/repository/com/sun/jersey/jersey-server/1.19.1/jersey-server-1.19.1.jar: zip file is empty

Getting this error even I have jersey-server in my .m2 repository. Please help me. Thanks in advance

**Comment by spencergibb** [comment]
Looks like a problem downloading a dependency with maven or Gradle. Delete that jar and try again? This isn't an issue with spring cloud Netflix
