### ISSUE TITLE
Spring cloud config uri configuration mistake existing in bootstrap.yml

### ISSUE THREAD

**Issue by Roger3581321** [spring-cloud-samples/eureka#50]
Hi,
  I found that there is a spring cloud config uri configuration mistake in bootstrap.yml as follows:
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
However, it should be http://localhost:8888 or ${CONFIG_SERVER_URL}.

**Comment by spencergibb** [comment]
This is not a mistake. It allows the url to be over ridden by an env var
