### ISSUE TITLE
Release eureka Spring Boot 2 to Docker Hub

### ISSUE THREAD

**Issue by aSemy** [spring-cloud-samples/eureka#52]
The last version released on Docker Hub was 5 years ago, and uses Spring Boot v1.2.3.

https://hub.docker.com/r/springcloud/eureka/tags?page=1&ordering=last_updated

 I see the current Spring Boot version on master branch is 2.0.2.RELEASE.

Please can you publish a newer version of springcloud/eureka to Docker Hub? 🙂

**Comment by sgflt** [comment]
Actually it is 9 years now. I think the image it is in DIY mode.

**Comment by spencergibb** [comment]
We won't be releasing any new images
