### ISSUE TITLE
Eureka RC1 Download: git-commit-id-plugin should be excluded

### ISSUE THREAD

**Issue by ewolff** [spring-cloud-samples/eureka#6]
If you download Eureka RC1 and import it into Eclipse the result is an Error:

.git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml (pl.project13.maven:git-commit-id-plugin:2.1.11:revision:default:initialize)	pom.xml	/eureka-1.0.0.RC1	line 14	Maven Build Problem

Solution: Remove git-commit-id-plugin plugin from pom.xml

i.e. for future releases this plugin should be removed in pom.xml IMHO

**Comment by ewolff** [comment]
The configserver example has the same issue.

**Comment by nomstradamus** [comment]
Faced the same issue. Used git clone and it worked.

**Comment by dsyer** [comment]
How do you mean "download"? You mean the github zipped bundle? I like that plugin, but it does suck a bit in this way. According to the plugin documentation you can add `<failOnNoGitDirectory>true</failOnNoGitDirectory>` to its configuration. Makes sense to me.

**Comment by dsyer** [comment]
That flag (set to "false" of course) should be in 1.0.1.

**Comment by ewolff** [comment]
@dsyer Thanks for looking into this! I was referring to the downlad at https://github.com/spring-cloud-samples/eureka/releases/tag/v1.0.0.RELEASE .
