### ISSUE TITLE
Error deploying two eureka clients in one container

### ISSUE THREAD

**Issue by vibhaanshu** [spring-cloud-samples/eureka#8]
Each war tries to register 'org.springframework.cloud.context.environment.EnvironmentManager' in jmx but there should be only one. 

Spring cloud version - 1.0.0.RC1

Refer below link for details:
http://stackoverflow.com/questions/28197414/spring-cloud-error-deploying-two-eureka-clients-in-one-container

**Comment by spencergibb** [comment]
moving to another repo issue tracker
